language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - PACKAGE_VERSION=high

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: PACKAGE_VERSION=low

before_script:
  - composer selfupdate
  - if [[ "$PACKAGE_VERSION" == "high" ]]; then composer update --prefer-dist; fi
  - if [[ "$PACKAGE_VERSION" == "low" ]]; then composer update --prefer-lowest --prefer-dist; fi
  - ./bin/jackrabbit.sh

script: vendor/bin/phpunit

notifications:
  irc: "irc.freenode.org#jackalope"

